services:
  - type: web
    name: user-auth-service
    runtime: docker
    dockerfilePath: ./services/user-auth/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: "production"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: PGSSLMODE
        value: "require"
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: MAX_FAILED_LOGIN_ATTEMPTS
        value: "5"
      - key: LOCK_TIME_LOGIN_WINDOW
        value: "15"
      - key: LOCK_USER_TIME
        value: "30"
      - key: LOG_LEVEL
        value: "DEBUG"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1

databases:
  - name: user-auth-db
    databaseName: db_ioio
    user: admin
    plan: free
    region: oregon