services:
  - type: web
    name: user-auth-service
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: docker build -t user-auth .
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PGSSLMODE
        value: require
      - key: DATABASE_URL
        fromDatabase:
          name: user-auth-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: MAX_FAILED_LOGIN_ATTEMPTS
        value: 5
      - key: LOCK_TIME_LOGIN_WINDOW
        value: 15
      - key: LOCK_USER_TIME
        value: 30
      - key: LOG_LEVEL
        value: DEBUG
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DB_USER
        sync: false
        fromService:
          type: database
          name: user-auth-db
          property: user
      - key: DB_PASSWORD
        sync: false
        fromService:
          type: database
          name: user-auth-db
          property: password
      - key: DB_HOST
        sync: false
        fromService:
          type: database
          name: user-auth-db
          property: host
      - key: DB_PORT
        sync: false
        fromService:
          type: database
          name: user-auth-db
          property: port
      - key: DB_NAME
        sync: false
        fromService:
          type: database
          name: user-auth-db
          property: database
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: user-auth-disk
      mountPath: /app/data
      sizeGB: 1

databases:
  - name: user-auth-db
    databaseName: user_auth
    user: user_auth
    plan: free
    region: oregon 