services:
  - type: web
    name: user-auth-service
    env: python
    pythonVersion: "3.10"
    rootDir: services/user-auth
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PGSSLMODE
        value: require
      - key: DATABASE_URL
        fromDatabase:
          name: user-auth-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: MAX_FAILED_LOGIN_ATTEMPTS
        value: 5
      - key: LOCK_TIME_LOGIN_WINDOW
        value: 15
      - key: LOCK_USER_TIME
        value: 30
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: user-auth-db
    databaseName: user_auth
    user: user_auth
    plan: free 