services:
  - type: web
    name: user-auth-service
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: docker-compose --profile app up -d
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PGSSLMODE
        value: require
      - key: DATABASE_URL
        sync: false
        value: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: MAX_FAILED_LOGIN_ATTEMPTS
        value: 5
      - key: LOCK_TIME_LOGIN_WINDOW
        value: 15
      - key: LOCK_USER_TIME
        value: 30
      - key: LOG_LEVEL
        value: DEBUG
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1

databases:
  - name: user-auth-db
    databaseName: db_ioio
    user: admin
    plan: free
    region: oregon 