services:
  user-profile-test:
    build: .
    command: ["/app/entrypoint.sh", "test"]
    environment:
      - ENVIRONMENT=test
    volumes:
      - .:/app
    profiles:
      - test

  user-profile:
    build: .
    command: ["/app/entrypoint.sh", "app"]
    environment:
      - DD_SERVICE=app
      - DD_ENV=${ENVIRONMENT}
    profiles:
      - app  
    ports:
      - "8080:8080"
    volumes:
      - .:/app
