version: '3.8'

services:
  user-profile:
    build: .
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=app
      - DD_ENV=${ENVIRONMENT}
    networks:
      - datadog-agent-monitoring
    ports:
      - "8080:8080"
    volumes:
      - .:/app

networks:
  datadog-agent-monitoring:
    external: true