name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - register-back
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: |
          cd services/user-auth
          black --check app tests

  start-docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create Docker network
        run: docker network create datadog-agent-monitoring

      - name: Copy environment variables
        run: |
          cp $GITHUB_WORKSPACE/services/user-auth/.env.example $GITHUB_WORKSPACE/services/user-auth/.env.development

      - name: Start Docker services
        run: |
          docker-compose -f $GITHUB_WORKSPACE/services/user-auth/docker-compose.yml --env-file $GITHUB_WORKSPACE/services/user-auth/.env.development up -d

      - name: Wait for API to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/health; then
              echo "API is ready"
              break
            fi
            echo "Waiting for API..."
            sleep 5
          done

  test:
    runs-on: ubuntu-latest
    needs: start-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd services/user-auth
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          cd services/user-auth
          PYTHONPATH=. pytest --cov=app --cov=tests --cov-report=term-missing --cov-report=xml --cov-report=html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  stop-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Recreate .env.development file
        run: |
          cp $GITHUB_WORKSPACE/services/user-auth/.env.example $GITHUB_WORKSPACE/services/user-auth/.env.development

      - name: Stop Docker services
        run: |
          docker-compose -f $GITHUB_WORKSPACE/services/user-auth/docker-compose.yml --env-file $GITHUB_WORKSPACE/services/user-auth/.env.development down

  deploy-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd services/user-auth
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Generate coverage report
        run: |
          cd services/user-auth
          PYTHONPATH=. pytest --cov=app --cov=tests --cov-report=html

      - name: Checkout GitHub Pages
        uses: actions/checkout@v4
        with:
          repository: memo2-2025-1c-group9/memo2-2025-1c-group9.github.io
          token: ${{ secrets.GH_PAT }}
          path: pages

      - name: Update coverage report
        run: |
          mkdir -p pages/coverages/user-auth
          cp -r services/user-auth/htmlcov/* pages/coverages/user-auth/

      - name: Commit and push changes
        working-directory: pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update coverage report for user-auth service"
          git push