name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - register-back
      - login-dev
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: |
          cd services/user-auth
          black --check app tests

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create Docker network
        run: docker network create datadog-agent-monitoring

      - name: Copy environment variables
        run: |
          cp $GITHUB_WORKSPACE/services/user-auth/.env.example $GITHUB_WORKSPACE/services/user-auth/.env.development

      - name: Start Docker services
        run: |
          cd $GITHUB_WORKSPACE/services/user-auth
          docker-compose --profile app up -d

      - name: Wait for API to be ready
        run: |
          cd $GITHUB_WORKSPACE/services/user-auth
          for i in {1..30}; do
            if curl -s http://localhost:8000/health; then
              echo "API is ready"
              exit 0
            fi
            echo "Waiting for API... Attempt $i/30"
            sleep 5
          done
          echo "API failed to start"
          docker-compose ps
          docker-compose logs
          exit 1

      - name: Install dependencies
        run: |
          cd services/user-auth
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/student_management
        run: |
          cd services/user-auth
          PYTHONPATH=. pytest --cov=app --cov=tests --cov-report=term-missing --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: services/user-auth/htmlcov/
          retention-days: 1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Stop Docker services
        run: |
          cd $GITHUB_WORKSPACE/services/user-auth
          docker-compose down

  deploy-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: services/user-auth/htmlcov

      - name: Checkout GitHub Pages
        uses: actions/checkout@v4
        with:
          repository: memo2-2025-1c-group9/memo2-2025-1c-group9.github.io
          token: ${{ secrets.GH_PAT }}
          path: pages

      - name: Update coverage report
        run: |
          mkdir -p pages/coverages/user-auth
          cp -r services/user-auth/htmlcov/* pages/coverages/user-auth/

      - name: Commit and push changes
        working-directory: pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update coverage report for user-auth service"
          git push