name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black
        run: black --check app tests

        
  start-docker-db:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create external network if not exists
        run: |
          docker network inspect datadog-agent-monitoring >/dev/null 2>&1 || \
          docker network create datadog-agent-monitoring

      - name: Copy environment variables
        run: cp .env.example .env.development

      - name: Start Docker DB service
        run: docker-compose up -d

      - name: Wait for DB to be ready
        run: |
          for i in {1..10}; do
            if docker exec student_management_db pg_isready -U user; then
              echo "Database is ready"
              break
            fi
            echo "Waiting for database..."
            sleep 5
          done
  test:
    runs-on: ubuntu-latest
    needs: start-docker-db
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          PYTHONPATH=. pytest --cov=app --cov=tests --cov-report=term-missing --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  stop-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Stop Docker services
        run: docker-compose down

  update-readme:
    runs-on: ubuntu-latest
    needs: stop-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Extract coverage percentage
        id: extract-coverage
        run: |
          COVERAGE=$(grep -oP 'line-rate="\K[0-9.]+' coverage.xml | awk '{print $1*100}' | head -n1 | tr -d '\n')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Generate badge URL
        run: |
          BADGE_URL="https://img.shields.io/badge/Coverage-${COVERAGE}%25-brightgreen"
          echo "Generated Badge URL: $BADGE_URL"
          echo "BADGE_URL=$BADGE_URL" >> $GITHUB_ENV

      - name: Update README with badge
        run: |
          sed -i "s|!\[Coverage\](.*)|![Coverage](${BADGE_URL})|" README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          TARGET_BRANCH=${{ github.head_ref || github.ref_name }}
          git fetch origin $TARGET_BRANCH
          git checkout $TARGET_BRANCH
          git pull origin $TARGET_BRANCH
          git add README.md
          git commit -m "Update coverage badge in README" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:$TARGET_BRANCH